site_name: The Quest for the Golden Tennis Ball
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: gtbLight
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: gtbDark
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - toc.follow

extra:
  status:
    cow: chicken
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/goldentennisball/
    - icon: fontawesome/brands/github
      link: https://github.com/theAdmiral21/Golden-Tennis-Ball-Devlog

extra_css:
  - stylesheets/gtb.css

docs_dir: docs

plugins:
  - search
  - awesome-pages
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      title: Site Contents
      permalink: true
      toc_depth: 3

nav:
  - "Home": "index.md"
  - "Devlog":
      - "Getting Started": "2025/11/18/firstPost.md"
      # - "Character Controllers": "CharacterController.md"
  - "Contact": "contact.md"
